apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth
  namespace: delivery-platform
spec:
  selector:
    matchLabels:
      app: order-service
  jwtRules:
    - issuer: "auth-service.delivery-platform.svc.cluster.local"
      jwksUri: "http://auth-service.delivery-platform.svc.cluster.local:8080/.well-known/jwks.json"
      forwardOriginalToken: true
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
  namespace: delivery-platform
spec:
  selector:
    matchLabels:
      app: order-service
  action: ALLOW
  rules:
    - from:
        - source:
            # 이 부분을 올바르게 수정했습니다.
            requestPrincipals: ["auth-service.delivery-platform.svc.cluster.local/*"]