# external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret                # 리소스 종류: "외부 비밀 가져오기 지시서"
metadata:
  name: app-config                   # 이 지시서의 이름
  namespace: production              # 이 지시서는 production 네임스페이스에서 작동함
spec:
  refreshInterval: 1h                # 1시간마다 원본 비밀이 바뀌었는지 확인하고 자동 동기화해줘
  secretStoreRef:                    # 사용할 출입증 지정
    name: kubernetes-backend         # 위에서 만든 "kubernetes-backend" 출입증을 사용해
    kind: SecretStore
  target:                            # 최종적으로 만들 결과물(쿠버네티스 Secret)에 대한 설정
    name: app-config-secret          # 만들어질 Secret의 이름은 "app-config-secret"으로 해줘(*)
    creationPolicy: Owner            # 이 ExternalSecret이 삭제되면, 만들어진 Secret도 자동으로 삭제해줘
  data:
  - secretKey: database-password     # 최종 Secret에 "database-password"라는 키를 만들어줘
    remoteRef:
      key: db-credentials            # 값은 "vault" 네임스페이스에 있는 "db-credentials" Secret에서 가져와
      property: password             # 그 Secret 안의 "password"라는 키의 값을 복사해줘