apiVersion: external-secrets.io/v1 # ESO가 사용하는 API 버전
kind: SecretStore # 리소스 종류: "비밀 저장소 접근 방법"
metadata:
  name: kubernetes-backend # 이 출입증의 이름
  namespace: production # 이 출입증은 production 네임스페이스에서만 유효함
spec:
  provider:
    kubernetes: # 이번에 사용할 외부 저장소는 "다른 쿠버네티스"임
      remoteNamespace: vault # "vault"라는 네임스페이스에 있는 Secret을 가져올 것
      auth:
        serviceAccount:
          name: external-secrets-sa # 이 출입증을 사용할 때의 신분은 external-secrets-sa 임
      server:
        caProvider: # 서버를 신뢰하기 위한 인증서 정보
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt