apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-nginx-config
  namespace: cloudmart
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        server {
            listen 8080;
            
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
            
            location /ready {
                access_log off;
                return 200 "ready\n";
                add_header Content-Type text/plain;
            }
            
            location /stub_status {
                stub_status;
                access_log off;
            }
            
            location / {
                return 200 "Product Service v1.0 - CloudMart\n";
                add_header Content-Type text/plain;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: cloudmart
  labels:
    app: product-service
    tier: backend
spec:
  replicas: 3 # 💡 User보다 많음 (상품 조회가 더 많아서)
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
        tier: backend
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: product-service
          image: nginx:alpine
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_NAME
              value: "product-service"
            - name: REDIS_HOST
              value: "redis-service" # 💡 Redis 캐시 사용 (빠른 조회)
          resources:
            requests:
              cpu: 150m # 💡 User보다 많음 (트래픽이 더 많아서)
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:0.11.0
          args:
            - -nginx.scrape-uri=http://localhost:8080/stub_status
          ports:
            - containerPort: 9113
              name: metrics
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 64Mi
      volumes:
        - name: nginx-config
          configMap:
            name: product-service-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: cloudmart
spec:
  selector:
    app: product-service
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 9113
      targetPort: 9113
      name: metrics
  type: ClusterIP
