apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server
  namespace: game-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - standard
      containers:
      - name: chat
        image: your-chat-image:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 1Gi  # 메모리 집약적