# user-service Deployment (DB 연결 환경변수 포함)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: nginx:alpine # 실제 서비스 이미지를 가정 (P. 7)
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: postgres-user-service.data.svc.cluster.local
        - name: DB_PORT
          value: "5432"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

---

# product-service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: nginx:alpine # 실제 서비스 이미지를 가정 (P. 8)
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_HOST
          value: mongodb-product-service.data.svc.cluster.local
        - name: MONGO_PORT
          value: "27017"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi