# networking/database-services.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-user-service
  namespace: data
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-user
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-product-service
  namespace: data
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb-product
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cache-service
  namespace: data
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-cache